### ISSUE TITLE
PR already exists or an error has occurred

### ISSUE THREAD

**Issue by RobinDink** [acraven/azure-dependabot#2]
Hey,

thank you for adding support for Azure DevOps to this awesome bot!
I have a problem where the bot recognizes that there are some outdated dependencies but doesn't create Pull Requests for them.

![image](https://user-images.githubusercontent.com/56680419/69525402-537df300-0f68-11ea-998a-c23ac7626db4.png)

Any idea on how to fix this?

Cheers,
Robin

**Comment by MO2k4** [comment]
Hey @RobCoPKC 

you need same more access rights for the user "Project Collection Build Service"

* Contribute to pull requests

and maybe CreateBranch - i am sure about this one.

Martin

**Comment by RobinDink** [comment]
Hey @MO2k4,

looks like the Build Service Account was missing the "Contribute to pull requests"-permission.
Thank you for your help!

Cheers,
Robin
